#!/bin/bash

set -eo pipefail

test -d admin && chmod -rx admin && mv admin .admin

# If MANTIS_ENABLE_ADMIN is set to 1, then enable the folder
if [ ! -z "$MANTIS_ENABLE_ADMIN" ] && [ "$MANTIS_ENABLE_ADMIN" -ne "0" ]; then
  test -d .admin && mv .admin admin && chmod +rx admin
fi

apache2-foreground
