version: "3"

services:

  testlink:
    image: testlink-app
    container_name: testlinkweb
    hostname: testlink
    ports:
      - "3000:80"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.6.29
    container_name: testlinkdb
    ports:
      - "3366:3306"
    environment:
      # Change root password before first run
      - MYSQL_ROOT_PASSWORD=2023root2023