version: "3"

services:

  testlink:
    image: testlink-app
    hostname: testlink
    ports:
    - "3000:80"
    links:
    - testlink-database
  testlink-database:
    image: mysql:5.6.29
    ports:
    - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Porzuczek2023!
